Exit ./configure with an error if redland libraries are not installed

diff --git a/R/redland/configure b/R/redland/configure
--- a/R/redland/configure
+++ b/R/redland/configure
@@ -2,5 +2,25 @@
 # This script is called by R package installation when
 # the command "R CMD INSTALL" is invoked.
 
+if ! [ -x "$(command -v pkg-config)" ]; then
+  echo ' '
+  echo 'ERROR: The program "pkg-config" cannot be found and is needed to build the redland R package.'
+  echo 'Please view the redland R package installation instructions at:'
+  echo '  https://github.com/ropensci/redland-bindings/tree/master/R/redland/README.md'
+  echo ' '
+  exit 1
+fi
+
+# Check if the redland package is installed
+pkg-config --exists redland
+if [ $? -ne 0 ]; then
+  echo ' '
+  echo 'ERROR: The redland libraries cannot be found and are needed to build the redland R package.'
+  echo 'Please view the redland R package installation instructions at:'
+  echo '  https://github.com/ropensci/redland-bindings/tree/master/R/redland/README.md'
+  echo ' '
+  exit 1
+fi
+
 cd tools && ./configure $* && make all
 cd ..
